python_version: 3.12
python_pip_version: 3.12
node_version: 20.15.0
nginx_version: 1.20.1

pizza_backend_repo_branch: dev_aws
pizza_eav_repo_branch: dev_aws
pizza_frontend_repo_branch: dev_aws

kendo_ui_license: "{{ lookup('amazon.aws.aws_secret', 'kendo-ui-license.key', region='ca-central-1', nested=True) }}"
django_secret_key: "{{ lookup('amazon.aws.aws_secret', 'Django-key.key', region='ca-central-1', nested=True) }}"

pizza_site_domain: 'dev.pizza.ca' 
gunicorn_debug: True

ebackend_db_host: 'pizza-dev-pizza-database-cluster.cluster-c16u8qequ389.ca-central-1.rds.amazonaws.com'
ebackend_db_name: 'ebackenddb'
ebackend_db_user: "{{ lookup('amazon.aws.aws_secret', 'rds!cluster-9da2da8c-eb1c-4b42-b04b-3a9d7d1154ac.username', region='ca-central-1', nested=True) }}"  
ebackend_db_password: "{{ lookup('amazon.aws.aws_secret', 'rds!cluster-9da2da8c-eb1c-4b42-b04b-3a9d7d1154ac.password', region='ca-central-1', nested=True) }}"

mail_relayhost: "smtp.pizza.ca"